export type CrypticProblem = {
  week: number;
  problem: string;
  answer: string;
  definitionPart: string;
  wordplayPart: string;
};

export const CRYPTIC_2026: CrypticProblem[] = [
  {
    week: 1,
    problem: "꼿꼿한 도장 식물",
    answer: "선인장",
    definitionPart: "식물",
    wordplayPart: "꼿꼿한 도장",
  },
  {
    week: 2,
    problem: "해적 나미의 소리에 애착이 가는 마음",
    answer: "정나미",
    definitionPart: "애착이 가는 마음",
    wordplayPart: "해적 나미의 소리",
  },
  {
    week: 3,
    problem: "채영이가 좋아하는 주택 종류",
    answer: "아파트",
    definitionPart: "주택 종류",
    wordplayPart: "채영이가 좋아하는",
  },
  {
    week: 4,
    problem: "불에 탄 파충류의 피를 먹는 종족",
    answer: "뱀파이어",
    definitionPart: "피를 먹는 종족",
    wordplayPart: "불에 탄 파충류",
  },
  {
    week: 5,
    problem: "종교에서 허락한 하루를 덧씌운 알",
    answer: "할랄",
    definitionPart: "종교에서 허락한",
    wordplayPart: "하루를 덧씌운 알",
  },
  {
    week: 6,
    problem: "굴을 강하게 만들어주는 액체",
    answer: "꿀",
    definitionPart: "액체",
    wordplayPart: "굴을 강하게 만들어주는",
  },
  {
    week: 7,
    problem: "1박일 횟수를 분석하는 예능 프로그램",
    answer: "일박이일",
    definitionPart: "예능 프로그램",
    wordplayPart: "1박일 횟수를 분석",
  },
  {
    week: 8,
    problem: "지구 중앙을 뒤집어 버린 범죄자",
    answer: "도적",
    definitionPart: "범죄자",
    wordplayPart: "지구 중앙을 뒤집어 버린",
  },
  {
    week: 9,
    problem: "그대 기억이 지난 사랑이 뾰족하게 돋힌 것",
    answer: "가시",
    definitionPart: "뾰족하게 돋힌 것",
    wordplayPart: "그대 기억이 지난 사랑이",
  },
  {
    week: 10,
    problem: "포차 사이에 비가 내리는 장소",
    answer: "포장마차",
    definitionPart: "장소",
    wordplayPart: "포차 사이에 비가 내리는",
  },
  {
    week: 11,
    problem: "튼튼한 전당의 머리가 기억됨",
    answer: "건강",
    definitionPart: "튼튼한",
    wordplayPart: "전당의 머리가 기억됨",
  },
  {
    week: 12,
    problem: "일본에서 좋아하는 스포츠",
    answer: "스키",
    definitionPart: "스포츠",
    wordplayPart: "일본에서 좋아하는",
  },
  {
    week: 13,
    problem: "피자를 거꾸로 뒤집은 열매",
    answer: "구기자",
    definitionPart: "열매",
    wordplayPart: "피자를 거꾸로 뒤집은",
  },
  {
    week: 14,
    problem: "3.1421 캐릭터",
    answer: "파이리",
    definitionPart: "캐릭터",
    wordplayPart: "3.1421",
  },
  {
    week: 15,
    problem: "길과 길이를 알려주는 리더",
    answer: "지도자",
    definitionPart: "리더",
    wordplayPart: "길과 길이를 알려주는",
  },
  {
    week: 16,
    problem: "공사장에서 볼 수 있는 식기류의 기상현상",
    answer: "포크레인",
    definitionPart: "공사장에서 볼 수 있는",
    wordplayPart: "식기류의 기상현상",
  },
  {
    week: 17,
    problem: "물결의 양쪽 끝에 남는 것",
    answer: "결과물",
    definitionPart: "끝에 남는 것",
    wordplayPart: "물결의 양쪽",
  },
  {
    week: 18,
    problem: "연강이 3개여도 듣고 해내려는 마음가짐",
    answer: "사명감",
    definitionPart: "해내려는 마음가짐",
    wordplayPart: "연강이 3개여도 듣고",
  },
  {
    week: 19,
    problem: "나를 부르는 소리에 대답하는 노래",
    answer: "가요",
    definitionPart: "노래",
    wordplayPart: "나를 부르는 소리에 대답",
  },
  {
    week: 20,
    problem: "소 또는 무의 지조의 상징",
    answer: "소나무",
    definitionPart: "지조의 상징",
    wordplayPart: "소 또는 무",
  },
  {
    week: 21,
    problem: "과일이 있는 다섯 개의 스토브",
    answer: "오렌지",
    definitionPart: "과일",
    wordplayPart: "다섯 개의 스토브",
  },
  {
    week: 22,
    problem: "올림픽에서 볼 수 있는 점 붙은 도미",
    answer: "도마",
    definitionPart: "올림픽에서 볼 수 있는",
    wordplayPart: "점 붙은 도미",
  },
  {
    week: 23,
    problem: "미루고 흔들어서 인간을 무섭게 하는 것",
    answer: "괴물",
    definitionPart: "인간을 무섭게 하는 것",
    wordplayPart: "미루고 흔들어서",
  },
  {
    week: 24,
    problem: "구리가 들어있는 부산 건물들",
    answer: "부동산",
    definitionPart: "건물들",
    wordplayPart: "구리가 들어있는 부산",
  },
  {
    week: 25,
    problem: "이중근호의 양 끝에서 볼 수 있는 동물",
    answer: "호랑이",
    definitionPart: "동물",
    wordplayPart: "이중근호의 양 끝에서 볼 수 있는",
  },
  {
    week: 26,
    problem: "꼬마가 반지를 오직 모음",
    answer: "아이",
    definitionPart: "꼬마",
    wordplayPart: "반지를 오직 모음",
  },
  {
    week: 27,
    problem: "사고 나는 꿩과 작은 새는 머리가 잘렸다",
    answer: "추리",
    definitionPart: "사고",
    wordplayPart: "나는 꿩과 작은 새는 머리가 잘렸다",
  },
  {
    week: 28,
    problem: "오른쪽 왼쪽 오른쪽 요리조리 섞인 단지",
    answer: "오로지",
    definitionPart: "단지",
    wordplayPart: "오른쪽 왼쪽 오른쪽 요리조리 섞인",
  },
  {
    week: 29,
    problem: "텅 빈 고백 속 정답",
    answer: "공백",
    definitionPart: "텅 빈",
    wordplayPart: "고백 속 정답",
  },
  {
    week: 30,
    problem: "달 착륙 돌입 . . . 부스터용 코어가 소실되었습니다! 안 됨",
    answer: "부착용",
    definitionPart: "달",
    wordplayPart: "착륙 돌입 . . . 부스터용 코어가 소실되었습니다! 안 됨",
  },
  {
    week: 31,
    problem: "새 해여 오너라, 학기초의 기수들을 맞이하자꾸나",
    answer: "해오라기",
    definitionPart: "새",
    wordplayPart: "새 해여 오너라, 학기초의 기수들을 맞이하자꾸나",
  },
  {
    week: 32,
    problem:
      "역대급 복장의 웨딩 플래너가 마지막 프로그램에서 닭볶음탕을 만들었다",
    answer: "급식대가",
    definitionPart: "프로그램에서 닭볶음탕을 만들었다",
    wordplayPart: "역대급 복장의 웨딩 플래너가 마지막",
  },
  {
    week: 33,
    problem: "금요일에 가서 돈 보관함",
    answer: "금고",
    definitionPart: "돈 보관함",
    wordplayPart: "금요일에 가서",
  },
];

export const CRYPTIC_PROBLEMS: Record<number, CrypticProblem[]> = {
  2026: CRYPTIC_2026,
};
